### ISSUE TITLE
CUDA out of memory for my own trained checkpoint files

### ISSUE THREAD

**Issue by saadehmd** [ethnhe/PVN3D#19]
This is strange but, i have been able to run all the checkpoint files provided by you, on my NVIDIA QUADRO T1000 4GiB, with a reasonable frame rate(2 FPS.) 
Then i trained using your training scripts on my own data and now while loading the checkpoint files i generated, the same GPU gives OUT OF MEMORY error. How is this possible if the model is the same ? And also, i tried running this same checkpoint on the other powerful SLURM GPUS( 2 ,  32GiB NVIDIA Tesla V100s ), that i used for training. And the inference time was as bad  11s / it   for test minbatch size = 1

I also checked my own data, the images i have are almost equal size in KBs to LINEMOD images. I am suspecting i might be doing something wrong while training.

**Comment by saadehmd** [comment]
Also, i noticed the following: - 
in the load_Checkpoint() function
try:
           # The checkpoint i trained always get loaded here  
         checkpoint = torch.load(filename)#, map_location='cpu')
except:
        # Your checkpoints are always loaded here 
        # If i don't catch the exception it gives raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file? for your checkpoint
        checkpoint = pkl.load(open(filename, "rb"))
        # Also if i load my checkpoint here, it's not loaded properly, just loaded as a random integer.
I am suspecting, there's a difference in the way, both checkpoints were saved.

**Comment by saadehmd** [comment]
I didn't notice it before but it's actually coming from eval_pose_parallel() function:
The meanshiftPyTorch.fit() is allocating some tensors that are unexpectedly huge. 
Can you tell what might be going wrong in the assignement of this 'Cr = C.view(N, 1, c).repeat(1, N, 1)'

File "/home/ahmad3/PVN3D/pvn3d/lib/utils/pvn3d_eval_utils.py", line 189, in eval_one_frame_pose_lm
    ctr, ctr_labels = ms.fit(pred_ctr[cls_msk, :])
  File "/home/ahmad3/PVN3D/pvn3d/lib/utils/meanshift_pytorch.py", line 34, in fit
    Cr = C.view(N, 1, c).repeat(1, N, 1)
RuntimeError: CUDA out of memory. Tried to allocate 1.69 GiB (GPU 0; 3.81 GiB total capacity; 1.85 GiB already allocated; 1022.19 MiB free; 2.77 MiB cached)

**Comment by ethnhe** [comment]
- We use ```pickle.dump()``` rather than ```torch.save()``` to save the trained checkpoint on our platform, which doesn't matter in your case.
- The meanshift_pytorch is a rough implementation of MeanShift algorithm, the ```Cr = C.view(N, 1, c).repeat(1, N, 1)``` will get a N*N*C tensor. If N, the number of points with the same predicted label is too large. It will trigger "CUDA out of memory". You can randomly sample some points before calling the function. You're also welcome to implement a better version of cuda MeanShift.

**Comment by Michael187-ctrl** [comment]
Hey saadehmd, can you please explain me how you created the training data for your own dataset?

**Comment by saadehmd** [comment]
I didn't notice it before but it's actually coming from eval_pose_parallel() function:
The meanshiftPyTorch.fit() is allocating some tensors that are unexpectedly huge. 
Can you tell what might be going wrong in the assignement of this 'Cr = C.view(N, 1, c).repeat(1, N, 1)'

File "/home/ahmad3/PVN3D/pvn3d/lib/utils/pvn3d_eval_utils.py", line 189, in eval_one_frame_pose_lm
    ctr, ctr_labels = ms.fit(pred_ctr[cls_msk, :])
  File "/home/ahmad3/PVN3D/pvn3d/lib/utils/meanshift_pytorch.py", line 34, in fit
    Cr = C.view(N, 1, c).repeat(1, N, 1)
RuntimeError: CUDA out of memory. Tried to allocate 1.69 GiB (GPU 0; 3.81 GiB total capacity; 1.85 GiB already allocated; 1022.19 MiB free; 2.77 MiB cached)

> Hey saadehmd, can you please explain me how you created the training data for your own dataset?

I collected all my data in gazebo using a kinect. Since i had accurate CAD models of all the target objects i was working with, i simply converted them to .obj files and placed them in gazebo with a bunch of different background environments. Any other light-weight rendering software like Open3D or PyRender could be used in the similar manner, I just used gazebo because there are readily avialble ros-based drivers and configuration files for kinect on gazebo's online tutorials, so i wouldn't have to setup a custom perspective camera in other rendering software. Also, since gazebo is a simulation engine with easy user-interaction where you could just simply pick and place a variety of background and foreground clutter objects and sorrounding environments without writing any extra lines of code. As for the data-collection protocol, i simply followed original YCB object dataset method. Sample rgb and depth images uniformly with camera-poses in upper hemisphere around the object. The object-label images can simply be obtained by projecting the XYZ points from .pcd(pointcloud) or points.txt of your target objects to their xy pixel coordinates (using ground truth pose of your object). I am still cleaning up the code a bit. i might push it on my branch by the end of this month. you can refer to that if it might be useful.

**Comment by saadehmd** [comment]
@ethnhe  Thanks for your help. this issue was solved. I was actually sampling the points wrong. For some reason my model, predicted all 12280 points to be object class and that was too huge for tensors allocated in meanshift algo.
